apps/crud/models.py
from datetime import datetime
from apps.app import db
from werkzeug.security import generate_password_hash
#db.Model을 상속한 크래스 작성
class User(db.Model):
    __tablename__ = "users"
    #컬럼명 정의
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String,index = True)
    email = db.Column(db.String,index = True)
    password_hash = db.Column(db.String)
    create_at = db.Column(db.DateTime,default = datetime.now)
    update_at = db.Column(db.DateTime,default = datetime.now,onupdate = datetime.now)

    @property
    def password(self):
        raise AttributeError('읽어 들일 수 없음')
    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField , StringField , SubmitField
from wtforms.validators import DataRequired , Email , length

#사용자 신규 작성 , 편집 폼 클래스
class UserForm(FlaskForm):
    username = StringField(
        "사용자명",
        validators=[
                DataRequired(message='사용자명은 필수입니다.'),
                length(max=30,message='30자 이내로 입력해주세요.')
        ]
    )

    email = StringField(
        '메일주소',
        validators=[
                DataRequired(message='메일주소는 필수입니다.'),
                Email(message='메일주소 형식으로 입력해주세요')
        ]
    )
    password = PasswordField(
        '비밀번호',
        validators=[
                DataRequired(message='비밀번호는 필수입니다')
        ]
    )

    submit = SubmitField('신규등록')

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Flask, Blueprint, render_template , redirect , url_for
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static"
)

@crud.route("/")
def index():
    print("!!!!!!!!")
    return render_template("crud/index.html")

@crud.route("/sql")
def sql():
    """user = User(
        username = '고재민',
        email = 'jmgo0625@gmail.com',
        userid = 'GJM',
        password_hash = '1111'
    )
    db.session.add(user)
    db.session.commit()
    db.session.query(User).all()
    db.session.query(User).filter_by(id = 1).all()"""
    db.session.query(User).filter_by(id = 1).delete()
    db.session.commit()
    return '콘솔 로그 확인!'

@crud.route('/users/new',methods=["GET","POST"])
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username = form.username.data,
            email = form.email.data,
            password_hash = form.password.data,
        )
        db.session.add(user)
        db.session.commit()
        
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html",form = form)

@crud.route('/users')
def users():
    users = User.query.all()
    return render_template('crud/index.html',users = users)

@crud.route('/user/<user_id>',methods = ["GET","POST"])
def edit_user(user_id):
    form = UserForm()
    user = User.query.filter_by(id=user_id).first()
    return render_template('crud/edit.html',user=user)

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <title>사용자 신규 작성</title>
    </head>
    <body>
        <h2>사용자 신규 작성</h2>
        <form action="{{url_for('crud.create_user')}}" method="POST" novalidate = "novalidate">
            {{form.csrf_token}}
            <p>
                {{form.username.label}} {{form.username(placeholder="사용자명")}}
            </p>
            {% for i in form.username.errors %}
            <span style="color: red;">{{i}}</span>
            {% endfor %}
            <p>
                {{form.email.label}} {{form.email(placeholder="메일주소")}}
            </p>
            {% for i in form.username.errors %}
            <span style="color: red;">{{i}}</span>
            {% endfor %}
            <p>
                {{form.password.label}} {{form.password(placeholder="비밀번호")}}
            </p>
            {% for i in form.username.errors %}
            <span style="color: red;">{{i}}</span>
            {% endfor %}
            <p>
                {{form.submit()}}
            </p>
        </form>
    </body>
</html>

apps/crud/templates/crud/edit.html
aaaa

apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html lang="'ko">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="{{url_for('crud.static',filename='style.css')}}" />
        <title>사용자 일람</title>
    </head>
    <body>
        <h2>사용자 일람</h2>
        <table>
            <tr>
                <th>사용자 ID</th>
                <th>사용자 명</th>
                <th>메일주소</th>
            </tr>
            {% for i in users %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td>{{ i.username }}</td>
                    <td>{{ i.email }}</td>
                </tr>
            {% endfor %}
        </table>
    </body>
</html>